### ISSUE TITLE
hCaptcha

### ISSUE THREAD

**Issue by mujehoxe** [dessant/buster#215] opened 2020-08-02 01:17 UTC
**Is your feature request related to a problem? Please describe.**

hCaptcha is becoming very common between websites 
**Describe the solution you'd like**

adding a feature to solve this types of captchas would be great

**Comment by crinny** [comment] 2020-08-12 07:25
Duplicate of https://github.com/dessant/buster/issues/204

**Closed** 2020-08-13 20:31 UTC

**Comment by dessant** [comment] 2020-08-13 20:36
I've talked before about why only reCAPTCHA is supported for now, and I'll write a wiki post about it when I find the time. In short, when a captcha service becomes abusive and does not let people pass like reCAPTCHA does, it becomes a candidate for supporting it in Buster.

As far as I know hCaptcha is doing things right, and you can even sign up to skip the captcha entirely if you can't solve visual challenges due to disabilities.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-09-25 14:26
Issue is tracked at #319.
